name: Use GitHub CLI in Workflow

on:
  workflow_dispatch:


jobs:
  get-codespaces:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API to list Codespaces
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Must be a PAT with codespace access
        run: |
          echo "Fetching Codespaces for authenticated user..."
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/Siegfred-Sambit/codespaces | jq
