name: Use GitHub CLI in Workflow

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use gh CLI to list issues
        run: gh issue list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
