name: Manual Plan Deployment

on: 
  workflow_dispatch:
    inputs:
      action-apply:
        description: 'Apply if true, Plan default'    
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

      path:
        description: 'pass the path to the file'    
        required: true
        default: ''
        type: string

permissions:
  contents: read
  pages: write
  packages: write

jobs:
  plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          ref: main

      - name: check branch
        if: ${{ github.event.inputs.git-ref }}
        run: |
          echo "Allowed only on main branch"
          echo "Inputs: "
          echo " -> Branch: ${{ github.ref }}"
          #exit 1

      - name: Execute the terraform-apply
        if: ${{ inputs.action-apply == true }}
        run:
          terragrunt apply --auto-approve --terragrunt-working-dir ${{ inputs.path }}

      - name: Execute the terraform-plan
        if: ${{ inputs.path == false }}
        run: 
          terragrunt apply --auto-approve --terragrunt-working-dir ${{ inputs.path }}
